export const SET_SHOPPING_CART = 'SET_SHOPPING_CART';
export const CLEAN_SHOPPING_CART = 'CLEAN_SHOPPING_CART';
export const DELETE_PIZZA = 'DELETE_PIZZA';
export const INCR_OR_DECR_COUNT = 'INCR_OR_DECR_COUNT';